### ISSUE TITLE
Pharmacophore from molecule node not working (default mapping?)

### ISSUE THREAD

**Issue by RossBio** [3D-e-Chem/knime-pharmacophore#12]
Generic sdf file input to the KNIME Pharmacophore from Molecule crashes, error from node is 
"ERROR Pharmacophore from molecule 2:2        Execute failed: Unknown type, should be one of AROM,HYBH,NEGC,HACC,HYBL,HDON,POSC,EXCL,LIPO" 

See attached WorkFlow

[Pharmtest.knwf.zip](https://github.com/3D-e-Chem/knime-pharmacophore/files/3631528/Pharmtest.knwf.zip)

**Comment by sverhoeven** [comment]
The molecule2pharmacophore node was only tested with output from the pharmacophore2molecule node which only produces has atoms. Your sdf file also has bonds section which the parser dies on.

**Comment by sverhoeven** [comment]
Version 1.0.4 of the pharmacophore nodes has been added to the https://3d-e-chem.github.io/updates software site

Could you try this version?

**Comment by RossBio** [comment]
Don't see that version in the update site, am only offered v 1.0.3

**Comment by sverhoeven** [comment]
Sorry, I only added it to the `https://3d-e-chem.github.io/updates` update site, which your probably are not using.

In a couple of hours the `KNIME Community Extensions (Experimental)` update site should have the new 3D-e-Chem v1.4.0 feature.

**Comment by RossBio** [comment]
I see it now, updated & works fine
Thanks
