### ISSUE TITLE
Possible bug: RMSD very high for a good fit

### ISSUE THREAD

**Issue by AJK-dev** [3D-e-Chem/knime-pharmacophore#6]
When aligning, for example, the KRIPO fragments 4xnv_BUR_frag1 and 5cu2_551_frag1 the fit seems good and it has a high KRIPO score (0.602), but the RMSD is very high (365.814).

**Comment by sverhoeven** [comment]
The RMSD is computed between pairs of pairs of points between the reference and the probe, these called cliques. 

These cliques consist of far fewer points that those used to calculate the KRIPO score.

See https://github.com/3D-e-Chem/knime-pharmacophore/blob/master/plugin/src/java/nl/esciencecenter/e3dchem/knime/pharmacophore/align/Aligner.java#L356-L367 for implmentation of RMSD.

**Comment by AJK-dev** [comment]
On line 357 the reference points of the best clique are selected instead of the probe points. So if I am not mistaking the transformation is applied to the reference points (instead of the probe points) and then again compared to the original reference point. This might explain the high RMSDs.

**Comment by sverhoeven** [comment]
The http://3d-e-chem.github.io/updates/ update site has new version of plugin with fix.
