### ISSUE TITLE
PharmacophorePoint#toArray method uses current locale

### ISSUE THREAD

**Issue by arofab** [3D-e-Chem/knime-pharmacophore#9]
The "Pharmacophore reader" node generates Pharmacophore cells whose point numbers are stored in current locale format. 
This cause failure during the execution of an "Extract pharmacophore points" node linked to a "Pharmacophore reader" output port, when current locale is not en-us (for example a locale using comma instead of dot for decimal separator).

The issue seem to be caused by PharmacophorePoint#toArray method, which does not use a DecimalFormat instance standardized to a locale, while PharmacophorePoint(String[]) constructor expects non-localized string representations.

**Comment by sverhoeven** [comment]
I have updated the toArray to use a '.' based locale. 
v1.0.2 was released and should become available in the [KNIME community contributions update site](https://www.knime.com/community) soonish.

Could you test it?

**Comment by arofab** [comment]
With the new release the issue has disappeared.
Thanks for the fast resolution.
